name: Scrape IG Feed

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm init -y && npm install node-fetch@2

      - name: Run scraper
        run: node scripts/update.js

      - name: Commit & Push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ig_posts.json
          git commit -m "Update IG feed $(date -u)" || echo "no changes"
          git push
